# Site settings
title: Electronic Ephemera
email: me@mercedescoyle.com
description: > 
  Data. Devops. Farming.
# baseurl: #none
url: http://mercedescoyle.com 
twitter_username: benzobot
github_username: mercul3s

# Build settings
markdown: kramdown

highlighter: rouge 

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

gems: [jekyll-paginate-v2]
